# MGS intersections

In [1]:
import sys; sys.path.append('..')
from crossreads_petrography import *

Loading config from /Users/ryan/github/crossreads-petrography/notebooks/../data/default_config.yaml

In [2]:
IsotopeConverter().path_output

'/Users/ryan/github/crossreads-petrography/data/Isotopes/output'

In [3]:
mgs = MgsConverter()
mgs

MgsConverter(
    path = "/Users/ryan/github/crossreads-petrography/data/MGS",
    path_input = "/Users/ryan/github/crossreads-petrography/data/MGS/input",
    path_output = "/Users/ryan/github/crossreads-petrography/data/MGS/output",
)

In [4]:
print(f"Docimium range: {mgs.df_ranges.loc['Docimium', 'wh_min']} - {mgs.df_ranges.loc['Docimium', 'wh_max']}")
print(f"Docimium box range: {mgs.df_ranges.loc['Docimium', 'box_min']} - {mgs.df_ranges.loc['Docimium', 'box_max']}")
print(f"Paros-1 range: {mgs.df_ranges.loc['Paros-1', 'wh_min']} - {mgs.df_ranges.loc['Paros-1', 'wh_max']}")
print(f"Paros-1 box range: {mgs.df_ranges.loc['Paros-1', 'box_min']} - {mgs.df_ranges.loc['Paros-1', 'box_max']}")

Calculating MGS ranges from input data
Loading MGS data from: /Users/ryan/github/crossreads-petrography/data/MGS/input
Loaded 65 rows of MGS data
Calculating MGS ranges from input data
Loading MGS data from: /Users/ryan/github/crossreads-petrography/data/MGS/input
Loaded 65 rows of MGS data
Calculating MGS ranges from input data
Loading MGS data from: /Users/ryan/github/crossreads-petrography/data/MGS/input
Loaded 65 rows of MGS data
Calculating MGS ranges from input data
Loading MGS data from: /Users/ryan/github/crossreads-petrography/data/MGS/input
Loaded 65 rows of MGS data
Calculating MGS ranges from input data
Loading MGS data from: /Users/ryan/github/crossreads-petrography/data/MGS/input
Loaded 65 rows of MGS data
Calculating MGS ranges from input data
Loading MGS data from: /Users/ryan/github/crossreads-petrography/data/MGS/input
Loaded 65 rows of MGS data
Calculating MGS ranges from input data
Loading MGS data from: /Users/ryan/github/crossreads-petrography/data/MGS/input
Loaded 65 rows of MGS data
Calculating MGS ranges from input data
Loading MGS data from: /Users/ryan/github/crossreads-petrography/data/MGS/input
Loaded 65 rows of MGS data

Docimium range: 0.278968983890681 - 2.0815444776525
Docimium box range: 0.49356126559544 - 1.58798075624329
Paros-1 range: 0.772531886695302 - 3.00429112526205
Paros-1 box range: 1.0085830691287 - 2.18884061850488

In [5]:
print(type(mgs.df_microscopy.loc['ISic000097', mgs.col_optical]))
print(type(mgs.df_microscopy.loc['ISic000097', mgs.col_digital]))
print(type(mgs.df_ranges.loc['Docimium', 'wh_min']))

Creating microscopy DataFrame from Metamorphic metadata
Reading metadata from /Users/ryan/github/crossreads-petrography/data/Metadata/Metamorphic.xlsx
Read 166 rows from metadata
33 samples with microscopy data
Creating microscopy DataFrame from Metamorphic metadata
Reading metadata from /Users/ryan/github/crossreads-petrography/data/Metadata/Metamorphic.xlsx
Read 166 rows from metadata
33 samples with microscopy data
Calculating MGS ranges from input data
Loading MGS data from: /Users/ryan/github/crossreads-petrography/data/MGS/input
Loaded 65 rows of MGS data

<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>

In [6]:
optical_value = mgs.df_microscopy.loc['ISic000097', mgs.col_optical]
digital_value = mgs.df_microscopy.loc['ISic000097', mgs.col_digital]
print(f"Optical value: {optical_value}")
print(f"Digital value: {digital_value}")

Creating microscopy DataFrame from Metamorphic metadata
Reading metadata from /Users/ryan/github/crossreads-petrography/data/Metadata/Metamorphic.xlsx
Read 166 rows from metadata
33 samples with microscopy data
Creating microscopy DataFrame from Metamorphic metadata
Reading metadata from /Users/ryan/github/crossreads-petrography/data/Metadata/Metamorphic.xlsx
Read 166 rows from metadata
33 samples with microscopy data

Optical value: 1.4
Digital value: 2.0

In [7]:
mgs.df_input

Loading MGS data from: /Users/ryan/github/crossreads-petrography/data/MGS/input
Loaded 65 rows of MGS data

    value_mm value_type   subtype
0   0.278969     min wh   Carrara
1   0.493561    min box   Carrara
2   0.708154     median   Carrara
3   1.008583    max box   Carrara
4   1.373389     max wh   Carrara
..       ...        ...       ...
60  0.858369     min wh  Thasos-3
61  1.566523    min box  Thasos-3
62  1.802573     median  Thasos-3
63  2.875534    max box  Thasos-3
64  3.197423     max wh  Thasos-3

[65 rows x 3 columns]

In [8]:
mgs.df_ranges

Calculating MGS ranges from input data
Loading MGS data from: /Users/ryan/github/crossreads-petrography/data/MGS/input
Loaded 65 rows of MGS data

                 wh_min     wh_max   box_min   box_max
subtype
Aphrodisias    0.257510   4.484978  1.373389  2.789699
Carrara        0.278969   1.373389  0.493561  1.008583
Docimium       0.278969   2.081544  0.493561  1.587981
Göktepe        0.343347   1.609441  0.493561  0.965665
Hymettus       0.343347   1.201716  0.450643  0.772532
Naxos          1.995708  12.000000  4.163090  7.575107
Paros-1        0.772532   3.004291  1.008583  2.188841
Paros-2 (3)    0.686695   4.570815  1.330471  3.068669
Paros-4        1.008583   3.004291  1.373389  2.575107
Pentelikon     0.278969   1.781116  0.686695  1.266093
Proconnesos-1  0.646695   4.484978  1.652360  3.197423
Thasos-1 (2)   1.786800   5.756773  2.537880  4.281400
Thasos-3       0.858369   3.197423  1.566523  2.875534

In [9]:
mgs.df_microscopy

Creating microscopy DataFrame from Metamorphic metadata
Reading metadata from /Users/ryan/github/crossreads-petrography/data/Metadata/Metamorphic.xlsx
Read 166 rows from metadata
33 samples with microscopy data

             optical microscopy MGS (mm)  digital microscopy MGS (mm)
ISic
ISic000097                          1.40                         2.00
ISic000104                          0.80                         0.60
ISic000107                           NaN                         1.60
ISic000121                          0.80                         2.20
ISic000132                           NaN                         1.50
ISic000139                           NaN                         2.00
ISic000139                           NaN                         2.10
ISic000148                          0.50                         0.60
ISic000151                           NaN                         0.35
ISic000154                           NaN                         1.30
ISic000161                           NaN                         0.90
ISic000162                           NaN                         0.75
ISic000163                           NaN                         0.90
ISic000164                           NaN                         1.20
ISic000172                           NaN                         1.70
ISic000178                           NaN                         0.50
ISic000181                           NaN                         0.20
ISic000181                           NaN                         0.30
ISic000184                           NaN                         0.50
ISic000184                           NaN                         0.50
ISic000195                           NaN                         2.30
ISic000207                           NaN                         0.60
ISic000208                           NaN                         2.00
ISic000216                           NaN                         0.30
ISic000220                           NaN                         0.30
ISic000227                           NaN                         0.50
ISic000229                           NaN                         0.60
ISic000232                           NaN                         0.40
ISic000579                          0.50                         0.30
ISic001140                           NaN                         2.10
ISic001143                           NaN                         0.30
ISic001158                           NaN                         0.50
ISic001435                          2.96                          NaN

In [10]:
mgs.df_output

Processing MGS intersections
Calculating MGS ranges from input data
Loading MGS data from: /Users/ryan/github/crossreads-petrography/data/MGS/input
Loaded 65 rows of MGS data
Creating microscopy DataFrame from Metamorphic metadata
Reading metadata from /Users/ryan/github/crossreads-petrography/data/Metadata/Metamorphic.xlsx
Read 166 rows from metadata
33 samples with microscopy data
Processed MGS intersections for 33 samples

Checking ISic000097 with optical value: 1.4
  Comparing with Docimium:
    Whisker: 0.278968983890681 <= 1.4 <= 2.0815444776525
    Box: 0.49356126559544 <= 1.4 <= 1.58798075624329
    Intersection: 🔬🔬
    Current cell value: 🔬🔬
Checking ISic000097 with optical value: 1.4
  Comparing with Paros-1:
    Whisker: 0.772531886695302 <= 1.4 <= 3.00429112526205
    Box: 1.0085830691287 <= 1.4 <= 2.18884061850488
    Intersection: 🔬🔬
    Current cell value: 🔬🔬
Checking ISic000097 with digital value: 2.0
  Comparing with Docimium:
    Whisker: 0.278968983890681 <= 2.0 <= 2.0815444776525
    Box: 0.49356126559544 <= 2.0 <= 1.58798075624329
    Intersection: 🔍
    Current cell value: 🔬🔬🔍
Checking ISic000097 with digital value: 2.0
  Comparing with Paros-1:
    Whisker: 0.772531886695302 <= 2.0 <= 3.00429112526205
    Box: 1.0085830691287 <= 2.0 <= 2.18884061850488
    Intersection: 🔍🔍
    Current cell value: 🔬🔬🔍🔍

subtype,Aphrodisias,Carrara,Docimium,Göktepe,Hymettus,Naxos,Paros-1,Paros-2 (3),Paros-4,Pentelikon,Proconnesos-1,Thasos-1 (2),Thasos-3
ISic,,,,,,,,,,,,,
ISic000097,🔬🔬🔍🔍,,🔬🔬🔍,🔬,,🔍,🔬🔬🔍🔍,🔬🔬🔍🔍,🔬🔬🔍🔍,🔬,🔬🔍🔍,🔍,🔬🔍🔍
ISic000104,🔬🔍,🔬🔬🔍🔍,🔬🔬🔍🔍,🔬🔬🔍🔍,🔬🔍🔍,,🔬,🔬,,🔬🔬🔍,🔬,,
ISic000121,🔬🔍🔍,🔬🔬,🔬🔬,🔬🔬,🔬,🔍,🔬🔍,🔬🔍🔍,🔍🔍,🔬🔬,🔬🔍🔍,🔍,🔍🔍
ISic000148,🔬🔍,🔬🔬🔍🔍,🔬🔬🔍🔍,🔬🔬🔍🔍,🔬🔬🔍🔍,,,,,🔬🔍,,,
ISic000579,🔬🔍,🔬🔬🔍,🔬🔬🔍,🔬🔬,🔬🔬,,,,,🔬🔍,,,
ISic001435,🔬,,,,,🔬,🔬,🔬🔬,🔬,,🔬🔬,🔬🔬,🔬
ISic000107,🔍🔍,,🔍,🔍,,,🔍🔍,🔍🔍,🔍🔍,🔍,🔍,,🔍🔍
ISic000132,🔍🔍,,🔍🔍,🔍,,,🔍🔍,🔍🔍,🔍🔍,🔍,🔍,,🔍
ISic000139,🔍🔍🔍🔍,,🔍,,,🔍🔍,🔍🔍🔍🔍,🔍🔍🔍🔍,🔍🔍🔍🔍,,🔍🔍🔍🔍,🔍🔍,🔍🔍🔍🔍
ISic000139,🔍🔍🔍🔍,,🔍,,,🔍🔍,🔍🔍🔍🔍,🔍🔍🔍🔍,🔍🔍🔍🔍,,🔍🔍🔍🔍,🔍🔍,🔍🔍🔍🔍
ISic000151,🔍,🔍,🔍,🔍,🔍,,,,,🔍,,,
ISic000154,🔍,🔍,🔍🔍,🔍,,,🔍🔍,🔍,🔍,🔍,🔍,,🔍
ISic000161,🔍,🔍🔍,🔍🔍,🔍🔍,🔍,,🔍,🔍,,🔍🔍,🔍,,🔍
ISic000162,🔍,🔍🔍,🔍🔍,🔍🔍,🔍🔍,,,🔍,,🔍🔍,🔍,,
ISic000163,🔍,🔍🔍,🔍🔍,🔍🔍,🔍,,🔍,🔍,,🔍🔍,🔍,,🔍
ISic000164,🔍,🔍,🔍🔍,🔍,🔍,,🔍🔍,🔍,🔍,🔍🔍,🔍,,🔍
ISic000172,🔍🔍,,🔍,,,,🔍🔍,🔍🔍,🔍🔍,🔍,🔍🔍,,🔍🔍
ISic000178,🔍,🔍🔍,🔍🔍,🔍🔍,🔍🔍,,,,,🔍,,,
ISic000181,🔍,🔍,🔍,,,,,,,🔍,,,
ISic000181,🔍,🔍,🔍,,,,,,,🔍,,,
ISic000184,🔍🔍,🔍🔍🔍🔍,🔍🔍🔍🔍,🔍🔍🔍🔍,🔍🔍🔍🔍,,,,,🔍🔍,,,
ISic000184,🔍🔍,🔍🔍🔍🔍,🔍🔍🔍🔍,🔍🔍🔍🔍,🔍🔍🔍🔍,,,,,🔍🔍,,,
ISic000195,🔍🔍,,,,,🔍,🔍,🔍🔍,🔍🔍,,🔍🔍,🔍,🔍🔍
ISic000207,🔍,🔍🔍,🔍🔍,🔍🔍,🔍🔍,,,,,🔍,,,
ISic000208,🔍🔍,,🔍,,,🔍,🔍🔍,🔍🔍,🔍🔍,,🔍🔍,🔍,🔍🔍
ISic000216,🔍,🔍,🔍,,,,,,,🔍,,,
ISic000220,🔍,🔍,🔍,,,,,,,🔍,,,
ISic000227,🔍,🔍🔍,🔍🔍,🔍🔍,🔍🔍,,,,,🔍,,,
ISic000229,🔍,🔍🔍,🔍🔍,🔍🔍,🔍🔍,,,,,🔍,,,
ISic000232,🔍,🔍,🔍,🔍,🔍,,,,,🔍,,,
ISic001140,🔍🔍,,,,,🔍,🔍🔍,🔍🔍,🔍🔍,,🔍🔍,🔍,🔍🔍
ISic001143,🔍,🔍,🔍,,,,,,,🔍,,,
ISic001158,🔍,🔍🔍,🔍🔍,🔍🔍,🔍🔍,,,,,🔍,,,

In [11]:
print(mgs.df_output.loc['ISic000097', ['Docimium', 'Paros-1']])

Processing MGS intersections
Calculating MGS ranges from input data
Loading MGS data from: /Users/ryan/github/crossreads-petrography/data/MGS/input
Loaded 65 rows of MGS data
Creating microscopy DataFrame from Metamorphic metadata
Reading metadata from /Users/ryan/github/crossreads-petrography/data/Metadata/Metamorphic.xlsx
Read 166 rows from metadata
33 samples with microscopy data

Checking ISic000097 with optical value: 1.4
  Comparing with Docimium:
    Whisker: 0.278968983890681 <= 1.4 <= 2.0815444776525
    Box: 0.49356126559544 <= 1.4 <= 1.58798075624329
    Intersection: 🔬🔬
    Current cell value: 🔬🔬
Checking ISic000097 with optical value: 1.4
  Comparing with Paros-1:
    Whisker: 0.772531886695302 <= 1.4 <= 3.00429112526205
    Box: 1.0085830691287 <= 1.4 <= 2.18884061850488
    Intersection: 🔬🔬
    Current cell value: 🔬🔬
Checking ISic000097 with digital value: 2.0
  Comparing with Docimium:
    Whisker: 0.278968983890681 <= 2.0 <= 2.0815444776525
    Box: 0.49356126559544 <= 2.0 <= 1.58798075624329
    Intersection: 🔍
    Current cell value: 🔬🔬🔍
Checking ISic000097 with digital value: 2.0
  Comparing with Paros-1:
    Whisker: 0.772531886695302 <= 2.0 <= 3.00429112526205
    Box: 1.0085830691287 <= 2.0 <= 2.18884061850488
    Intersection: 🔍🔍
    Current cell value: 🔬🔬🔍🔍

Processed MGS intersections for 33 samples

subtype
Docimium     🔬🔬🔍
Paros-1     🔬🔬🔍🔍
Name: ISic000097, dtype: object

In [12]:
print(mgs.df_output.index)
print(mgs.df_output.columns)

Processing MGS intersections
Calculating MGS ranges from input data
Loading MGS data from: /Users/ryan/github/crossreads-petrography/data/MGS/input
Loaded 65 rows of MGS data
Creating microscopy DataFrame from Metamorphic metadata
Reading metadata from /Users/ryan/github/crossreads-petrography/data/Metadata/Metamorphic.xlsx
Read 166 rows from metadata
33 samples with microscopy data

Checking ISic000097 with optical value: 1.4
  Comparing with Docimium:
    Whisker: 0.278968983890681 <= 1.4 <= 2.0815444776525
    Box: 0.49356126559544 <= 1.4 <= 1.58798075624329
    Intersection: 🔬🔬
    Current cell value: 🔬🔬
Checking ISic000097 with optical value: 1.4
  Comparing with Paros-1:
    Whisker: 0.772531886695302 <= 1.4 <= 3.00429112526205
    Box: 1.0085830691287 <= 1.4 <= 2.18884061850488
    Intersection: 🔬🔬
    Current cell value: 🔬🔬
Checking ISic000097 with digital value: 2.0
  Comparing with Docimium:
    Whisker: 0.278968983890681 <= 2.0 <= 2.0815444776525
    Box: 0.49356126559544 <= 2.0 <= 1.58798075624329
    Intersection: 🔍
    Current cell value: 🔬🔬🔍
Checking ISic000097 with digital value: 2.0
  Comparing with Paros-1:
    Whisker: 0.772531886695302 <= 2.0 <= 3.00429112526205
    Box: 1.0085830691287 <= 2.0 <= 2.18884061850488
    Intersection: 🔍🔍
    Current cell value: 🔬🔬🔍🔍

Processed MGS intersections for 33 samples
Processing MGS intersections

Index(['ISic000097', 'ISic000104', 'ISic000121', 'ISic000148', 'ISic000579',
       'ISic001435', 'ISic000107', 'ISic000132 ', 'ISic000139', 'ISic000139',
       'ISic000151', 'ISic000154', 'ISic000161', 'ISic000162', 'ISic000163',
       'ISic000164', 'ISic000172', 'ISic000178', 'ISic000181', 'ISic000181',
       'ISic000184', 'ISic000184', 'ISic000195', 'ISic000207', 'ISic000208',
       'ISic000216', 'ISic000220', 'ISic000227', 'ISic000229', 'ISic000232',
       'ISic001140', 'ISic001143', 'ISic001158'],
      dtype='object', name='ISic')

Calculating MGS ranges from input data
Loading MGS data from: /Users/ryan/github/crossreads-petrography/data/MGS/input
Loaded 65 rows of MGS data
Creating microscopy DataFrame from Metamorphic metadata
Reading metadata from /Users/ryan/github/crossreads-petrography/data/Metadata/Metamorphic.xlsx
Read 166 rows from metadata
33 samples with microscopy data

Checking ISic000097 with optical value: 1.4
  Comparing with Docimium:
    Whisker: 0.278968983890681 <= 1.4 <= 2.0815444776525
    Box: 0.49356126559544 <= 1.4 <= 1.58798075624329
    Intersection: 🔬🔬
    Current cell value: 🔬🔬
Checking ISic000097 with optical value: 1.4
  Comparing with Paros-1:
    Whisker: 0.772531886695302 <= 1.4 <= 3.00429112526205
    Box: 1.0085830691287 <= 1.4 <= 2.18884061850488
    Intersection: 🔬🔬
    Current cell value: 🔬🔬
Checking ISic000097 with digital value: 2.0
  Comparing with Docimium:
    Whisker: 0.278968983890681 <= 2.0 <= 2.0815444776525
    Box: 0.49356126559544 <= 2.0 <= 1.58798075624329
    Intersection: 🔍
    Current cell value: 🔬🔬🔍
Checking ISic000097 with digital value: 2.0
  Comparing with Paros-1:
    Whisker: 0.772531886695302 <= 2.0 <= 3.00429112526205
    Box: 1.0085830691287 <= 2.0 <= 2.18884061850488
    Intersection: 🔍🔍
    Current cell value: 🔬🔬🔍🔍

Processed MGS intersections for 33 samples

Index(['Aphrodisias', 'Carrara', 'Docimium', 'Göktepe', 'Hymettus', 'Naxos',
       'Paros-1', 'Paros-2 (3)', 'Paros-4', 'Pentelikon', 'Proconnesos-1',
       'Thasos-1 (2)', 'Thasos-3'],
      dtype='object', name='subtype')

In [13]:
# Add this at the end of the df_output property method
print(f"Final DataFrame for ISic000097:")
print(mgs.df_output.loc['ISic000097'])

Processing MGS intersections
Calculating MGS ranges from input data
Loading MGS data from: /Users/ryan/github/crossreads-petrography/data/MGS/input
Loaded 65 rows of MGS data
Creating microscopy DataFrame from Metamorphic metadata
Reading metadata from /Users/ryan/github/crossreads-petrography/data/Metadata/Metamorphic.xlsx

Final DataFrame for ISic000097:

Read 166 rows from metadata
33 samples with microscopy data
Processed MGS intersections for 33 samples

Checking ISic000097 with optical value: 1.4
  Comparing with Docimium:
    Whisker: 0.278968983890681 <= 1.4 <= 2.0815444776525
    Box: 0.49356126559544 <= 1.4 <= 1.58798075624329
    Intersection: 🔬🔬
    Current cell value: 🔬🔬
Checking ISic000097 with optical value: 1.4
  Comparing with Paros-1:
    Whisker: 0.772531886695302 <= 1.4 <= 3.00429112526205
    Box: 1.0085830691287 <= 1.4 <= 2.18884061850488
    Intersection: 🔬🔬
    Current cell value: 🔬🔬
Checking ISic000097 with digital value: 2.0
  Comparing with Docimium:
    Whisker: 0.278968983890681 <= 2.0 <= 2.0815444776525
    Box: 0.49356126559544 <= 2.0 <= 1.58798075624329
    Intersection: 🔍
    Current cell value: 🔬🔬🔍
Checking ISic000097 with digital value: 2.0
  Comparing with Paros-1:
    Whisker: 0.772531886695302 <= 2.0 <= 3.00429112526205
    Box: 1.0085830691287 <= 2.0 <= 2.18884061850488
    Intersection: 🔍🔍
    Current cell value: 🔬🔬🔍🔍
subtype
Aphrodisias      🔬🔬🔍🔍
Carrara
Docimium          🔬🔬🔍
Göktepe             🔬
Hymettus
Naxos               🔍
Paros-1          🔬🔬🔍🔍
Paros-2 (3)      🔬🔬🔍🔍
Paros-4          🔬🔬🔍🔍
Pentelikon          🔬
Proconnesos-1     🔬🔍🔍
Thasos-1 (2)        🔍
Thasos-3          🔬🔍🔍
Name: ISic000097, dtype: object

In [14]:
print(mgs.df_output.loc['ISic000097', 'Docimium'])
print(mgs.df_output.loc['ISic000097', 'Paros-1'])

Processing MGS intersections
Calculating MGS ranges from input data
Loading MGS data from: /Users/ryan/github/crossreads-petrography/data/MGS/input
Loaded 65 rows of MGS data
Creating microscopy DataFrame from Metamorphic metadata
Reading metadata from /Users/ryan/github/crossreads-petrography/data/Metadata/Metamorphic.xlsx
Read 166 rows from metadata
33 samples with microscopy data
Processed MGS intersections for 33 samples

Checking ISic000097 with optical value: 1.4
  Comparing with Docimium:
    Whisker: 0.278968983890681 <= 1.4 <= 2.0815444776525
    Box: 0.49356126559544 <= 1.4 <= 1.58798075624329
    Intersection: 🔬🔬
    Current cell value: 🔬🔬
Checking ISic000097 with optical value: 1.4
  Comparing with Paros-1:
    Whisker: 0.772531886695302 <= 1.4 <= 3.00429112526205
    Box: 1.0085830691287 <= 1.4 <= 2.18884061850488
    Intersection: 🔬🔬
    Current cell value: 🔬🔬
Checking ISic000097 with digital value: 2.0
  Comparing with Docimium:
    Whisker: 0.278968983890681 <= 2.0 <= 2.0815444776525
    Box: 0.49356126559544 <= 2.0 <= 1.58798075624329
    Intersection: 🔍
    Current cell value: 🔬🔬🔍
Checking ISic000097 with digital value: 2.0
  Comparing with Paros-1:
    Whisker: 0.772531886695302 <= 2.0 <= 3.00429112526205
    Box: 1.0085830691287 <= 2.0 <= 2.18884061850488
    Intersection: 🔍🔍
    Current cell value: 🔬🔬🔍🔍

Processing MGS intersections
Calculating MGS ranges from input data
Loading MGS data from: /Users/ryan/github/crossreads-petrography/data/MGS/input
Loaded 65 rows of MGS data
Creating microscopy DataFrame from Metamorphic metadata
Reading metadata from /Users/ryan/github/crossreads-petrography/data/Metadata/Metamorphic.xlsx
Read 166 rows from metadata
33 samples with microscopy data
Processed MGS intersections for 33 samples

🔬🔬🔍
Checking ISic000097 with optical value: 1.4
  Comparing with Docimium:
    Whisker: 0.278968983890681 <= 1.4 <= 2.0815444776525
    Box: 0.49356126559544 <= 1.4 <= 1.58798075624329
    Intersection: 🔬🔬
    Current cell value: 🔬🔬
Checking ISic000097 with optical value: 1.4
  Comparing with Paros-1:
    Whisker: 0.772531886695302 <= 1.4 <= 3.00429112526205
    Box: 1.0085830691287 <= 1.4 <= 2.18884061850488
    Intersection: 🔬🔬
    Current cell value: 🔬🔬
Checking ISic000097 with digital value: 2.0
  Comparing with Docimium:
    Whisker: 0.278968983890681 <= 2.0 <= 2.0815444776525
    Box: 0.49356126559544 <= 2.0 <= 1.58798075624329
    Intersection: 🔍
    Current cell value: 🔬🔬🔍
Checking ISic000097 with digital value: 2.0
  Comparing with Paros-1:
    Whisker: 0.772531886695302 <= 2.0 <= 3.00429112526205
    Box: 1.0085830691287 <= 2.0 <= 2.18884061850488
    Intersection: 🔍🔍
    Current cell value: 🔬🔬🔍🔍
🔬🔬🔍🔍

In [15]:
mgs.run()

Running MGS intersections
Saving MGS intersections
Processing MGS intersections
Calculating MGS ranges from input data
Loading MGS data from: /Users/ryan/github/crossreads-petrography/data/MGS/input
Loaded 65 rows of MGS data
Creating microscopy DataFrame from Metamorphic metadata
Reading metadata from /Users/ryan/github/crossreads-petrography/data/Metadata/Metamorphic.xlsx
Read 166 rows from metadata
33 samples with microscopy data
Processed MGS intersections for 33 samples
Saved MGS intersections to /Users/ryan/github/crossreads-petrography/data/MGS/output/2024-08-30/mgs_intersections.xlsx
MGS intersections processing completed

Checking ISic000097 with optical value: 1.4
  Comparing with Docimium:
    Whisker: 0.278968983890681 <= 1.4 <= 2.0815444776525
    Box: 0.49356126559544 <= 1.4 <= 1.58798075624329
    Intersection: 🔬🔬
    Current cell value: 🔬🔬
Checking ISic000097 with optical value: 1.4
  Comparing with Paros-1:
    Whisker: 0.772531886695302 <= 1.4 <= 3.00429112526205
    Box: 1.0085830691287 <= 1.4 <= 2.18884061850488
    Intersection: 🔬🔬
    Current cell value: 🔬🔬
Checking ISic000097 with digital value: 2.0
  Comparing with Docimium:
    Whisker: 0.278968983890681 <= 2.0 <= 2.0815444776525
    Box: 0.49356126559544 <= 2.0 <= 1.58798075624329
    Intersection: 🔍
    Current cell value: 🔬🔬🔍
Checking ISic000097 with digital value: 2.0
  Comparing with Paros-1:
    Whisker: 0.772531886695302 <= 2.0 <= 3.00429112526205
    Box: 1.0085830691287 <= 2.0 <= 2.18884061850488
    Intersection: 🔍🔍
    Current cell value: 🔬🔬🔍🔍