# Crossreads Petrography: pXRF Processing

In [1]:
import sys

sys.path.append("..")

import pandas as pd

from crossreads_petrography.pxrf import PXRFConverter

pd.options.display.max_columns = 1000

Loading config from /Volumes/machina/developer/github.com/kingsdigitallab/crossreads/petrography/notebooks/../data/default_config.yaml

In [2]:
xrf = PXRFConverter()
xrf

PXRFConverter(
    path = "/Volumes/machina/developer/github.com/kingsdigitallab/crossreads/petrography/data/pXRF",
    path_descriptions = "/Volumes/machina/developer/github.com/kingsdigitallab/crossreads/petrography/data/pXRF/pXRF Logbook.xlsx",
    path_input = "/Volumes/machina/developer/github.com/kingsdigitallab/crossreads/petrography/data/pXRF/input",
    path_output = "/Volumes/machina/developer/github.com/kingsdigitallab/crossreads/petrography/data/pXRF/output",
    path_standards = "/Volumes/machina/developer/github.com/kingsdigitallab/crossreads/petrography/data/pXRF/pXRF Standards.xlsx",
)

In [3]:
xrf.get_description('Isic001838', 'c')

Loading pXRF descriptions

'white, support of globe, left'

In [4]:
# xrf.valid_elements

In [5]:
xrf.df_standards

Loading pXRF standard values

Unnamed: 0,0CC,10CC,20CC,30CC,40CC,50CC,60CC,70CC,80CC,90CC,100CC
Element,,,,,,,,,,,
SiO2,91.040645,84.721351,78.817028,73.795328,64.449734,55.454155,32.568351,27.167883,21.531343,11.572406,1.000000e-08
K2O,6.002285,5.585656,5.196385,4.865306,4.249153,3.656077,2.147222,1.791171,1.419556,0.762966,1.000000e-08
CaO,0.958449,7.880084,14.336479,19.820316,30.009677,39.799615,64.641336,70.491810,76.593960,87.366212,9.987017e+01
Fe2O3,1.998622,1.812909,1.650108,1.519050,1.291436,1.090152,0.643091,0.549136,0.455141,0.298417,1.298312e-01
Ba,120.000000,107.870481,97.275091,88.771005,74.055316,61.098357,32.508134,26.532239,20.565139,10.640721,0.000000e+00
Ce,195.000000,175.289532,158.072023,144.252883,120.339889,99.284830,52.825719,43.114889,33.418351,17.291171,0.000000e+00
Co,4.000000,3.595683,3.242503,2.959033,2.468511,2.036612,1.083604,0.884408,0.685505,0.354691,0.000000e+00
Cr,12.000000,10.787048,9.727509,8.877100,7.405532,6.109836,3.250813,2.653224,2.056514,1.064072,0.000000e+00
Cu,12.000000,10.790000,9.730000,8.880000,7.410000,6.110000,3.250000,2.650000,2.060000,1.060000,0.000000e+00
Fe,14261.000000,12890.263285,11692.895909,10731.863281,9068.867850,7604.623464,4373.690099,3698.364127,3024.032108,1902.490132,7.000000e+02
Mn,155.000000,140.105962,127.095705,116.653396,98.583757,82.673691,47.567280,40.229379,32.902277,20.715919,7.650000e+00
Ti,540.000000,488.095767,442.756327,406.365924,343.395040,287.950052,165.607726,140.035873,114.501658,72.033418,2.650000e+01
La,109.000000,97.982354,88.358208,80.633663,67.266912,55.497674,29.528222,24.100117,18.680001,9.665321,0.000000e+00
Nb,53.000000,47.642796,42.963165,39.207194,32.707765,26.985108,14.357759,11.718406,9.082936,4.699652,0.000000e+00
Ni,8.000000,7.191365,6.485006,5.918067,4.937021,4.073224,2.167209,1.768816,1.371009,0.709381,0.000000e+00
Pb,40.000000,35.956827,32.425030,29.590335,24.685105,20.366119,10.836045,8.844080,6.855046,3.546907,0.000000e+00
Rb,320.000000,287.654616,259.400243,236.722679,197.480843,162.928951,86.688359,70.752638,54.840371,28.375256,0.000000e+00
Sr,10.000000,14.144252,17.764344,20.669907,25.697767,30.124728,39.893054,41.934818,43.973577,47.364420,5.100000e+01
Th,51.000000,45.844954,41.341914,37.727677,31.473509,25.966802,13.815957,11.276202,8.740184,4.522306,0.000000e+00
V,2.000000,1.797841,1.621252,1.479517,1.234255,1.018306,0.541802,0.442204,0.342752,0.177345,0.000000e+00
Y,143.000000,128.545657,115.919483,105.785447,88.249252,72.808875,38.738860,31.617585,24.506791,12.680192,0.000000e+00
Zn,50.000000,44.946034,40.531288,36.987919,30.856382,25.457649,13.545056,11.055100,8.568808,4.433634,0.000000e+00
Zr,300.000000,269.676203,243.187728,221.927512,185.138290,152.745892,81.270336,66.330598,51.412848,26.601802,0.000000e+00
Hg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df_desc = xrf.df_descriptions
df_desc[df_desc.Isic.str.contains("1838")]

,M window,M settings,site,day,month,year,cass,inv/id,Isic,count analyses,metamorphic/sedimentary/other,pigment?,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z
2,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
demo,replacement,"15, 35",centuripe,30,10,2023,,KA0843,ISic001838,6.0,m,,"white, top right corner","white, top centre","white, support of globe, left","gold, C","gold, R","gold, O",,,,,,,,,,,,,,,,,,,,

In [7]:
# xrf.df_adjusted

In [8]:
# df = xrf.get_df_adjusted()
# df[df.Isic.str.contains('1838')]
# df[(df.Isic.str.contains('1838')) & (df.desc!='')]

In [9]:
# df[df.desc_category!='']

## Descriptions

This file lives on Google Drive on the Crossreads team drive. It contains notes about the samples, including the Isic codes.

In [10]:
df = xrf.df_descriptions
df

,M window,M settings,site,day,month,year,cass,inv/id,Isic,count analyses,metamorphic/sedimentary/other,pigment?,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z
2,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
demo,original,"15, 20",marpo,4,10,2022,mag B,orsi316,Isic001923,3.0,,,"grey, thickness","grey, thickness","grey, thickness",,,,,,,,,,,,,,,,,,,,,,,
demo,replacement,"15, 35",REF,14,2,2025,,pietra di noto,CN,,s,,"cream, sample","cream, sample","cream, sample",,,,,,,,,,,,,,,,,,,,,,,
demo,replacement,"15, 35",REF,14,2,2025,,comiso,COM,,s,,"cream, sample","cream, sample","cream, sample",,,,,,,,,,,,,,,,,,,,,,,
demo,replacement,"15, 35",CT,27,3,2024,,exmft020,CTexmft020,1.0,,y,"rubr, pigment",,,,,,,,,,,,,,,,,,,,,,,,,
demo,replacement,"15, 35",CT,27,3,2024,,exmft129,CTexmft129,2.0,,y,"white, end of l 4","rubr, pigment",,,,,,,,,,,,,,,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
demo,original,"15, 20",pcas,23,3,2022,1,smg206,pcassmg206,3.0,,,"wh, v","dark, v","dark, between letters",,,,,,,,,,,,,,,,,,,,,,,
demo,replacement,"15, 35",REF,14,2,2025,,noto biancastra,PNB,,s,,"white, sample","white, sample","white, sample",,,,,,,,,,,,,,,,,,,,,,,
demo,replacement,"15, 35",REF,14,2,2025,,noto giallastra,PNG,,s,,"cream, sample","cream, sample","cream, sample",,,,,,,,,,,,,,,,,,,,,,,
demo,replacement,"15, 35",REF,14,2,2025,,sabucina,SAB,,s,,"yellow, sample","yellow, sample","yellow, sample",,,,,,,,,,,,,,,,,,,,,,,
demo,replacement,"15, 35",REF,14,2,2025,,calcare tenero scicli,SCI,,s,,"cream, sample","cream, sample","cream, sample",,,,,,,,,,,,,,,,,,,,,,,

## Standards

In [11]:
xrf.df_standards

Unnamed: 0,0CC,10CC,20CC,30CC,40CC,50CC,60CC,70CC,80CC,90CC,100CC
Element,,,,,,,,,,,
SiO2,91.040645,84.721351,78.817028,73.795328,64.449734,55.454155,32.568351,27.167883,21.531343,11.572406,1.000000e-08
K2O,6.002285,5.585656,5.196385,4.865306,4.249153,3.656077,2.147222,1.791171,1.419556,0.762966,1.000000e-08
CaO,0.958449,7.880084,14.336479,19.820316,30.009677,39.799615,64.641336,70.491810,76.593960,87.366212,9.987017e+01
Fe2O3,1.998622,1.812909,1.650108,1.519050,1.291436,1.090152,0.643091,0.549136,0.455141,0.298417,1.298312e-01
Ba,120.000000,107.870481,97.275091,88.771005,74.055316,61.098357,32.508134,26.532239,20.565139,10.640721,0.000000e+00
Ce,195.000000,175.289532,158.072023,144.252883,120.339889,99.284830,52.825719,43.114889,33.418351,17.291171,0.000000e+00
Co,4.000000,3.595683,3.242503,2.959033,2.468511,2.036612,1.083604,0.884408,0.685505,0.354691,0.000000e+00
Cr,12.000000,10.787048,9.727509,8.877100,7.405532,6.109836,3.250813,2.653224,2.056514,1.064072,0.000000e+00
Cu,12.000000,10.790000,9.730000,8.880000,7.410000,6.110000,3.250000,2.650000,2.060000,1.060000,0.000000e+00
Fe,14261.000000,12890.263285,11692.895909,10731.863281,9068.867850,7604.623464,4373.690099,3698.364127,3024.032108,1902.490132,7.000000e+02
Mn,155.000000,140.105962,127.095705,116.653396,98.583757,82.673691,47.567280,40.229379,32.902277,20.715919,7.650000e+00
Ti,540.000000,488.095767,442.756327,406.365924,343.395040,287.950052,165.607726,140.035873,114.501658,72.033418,2.650000e+01
La,109.000000,97.982354,88.358208,80.633663,67.266912,55.497674,29.528222,24.100117,18.680001,9.665321,0.000000e+00
Nb,53.000000,47.642796,42.963165,39.207194,32.707765,26.985108,14.357759,11.718406,9.082936,4.699652,0.000000e+00
Ni,8.000000,7.191365,6.485006,5.918067,4.937021,4.073224,2.167209,1.768816,1.371009,0.709381,0.000000e+00
Pb,40.000000,35.956827,32.425030,29.590335,24.685105,20.366119,10.836045,8.844080,6.855046,3.546907,0.000000e+00
Rb,320.000000,287.654616,259.400243,236.722679,197.480843,162.928951,86.688359,70.752638,54.840371,28.375256,0.000000e+00
Sr,10.000000,14.144252,17.764344,20.669907,25.697767,30.124728,39.893054,41.934818,43.973577,47.364420,5.100000e+01
Th,51.000000,45.844954,41.341914,37.727677,31.473509,25.966802,13.815957,11.276202,8.740184,4.522306,0.000000e+00
V,2.000000,1.797841,1.621252,1.479517,1.234255,1.018306,0.541802,0.442204,0.342752,0.177345,0.000000e+00
Y,143.000000,128.545657,115.919483,105.785447,88.249252,72.808875,38.738860,31.617585,24.506791,12.680192,0.000000e+00
Zn,50.000000,44.946034,40.531288,36.987919,30.856382,25.457649,13.545056,11.055100,8.568808,4.433634,0.000000e+00
Zr,300.000000,269.676203,243.187728,221.927512,185.138290,152.745892,81.270336,66.330598,51.412848,26.601802,0.000000e+00
Hg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## pXRF input data

Two kinds of files:
* "MK" files
    * Filename must start with 
    * Only Si, K, Ca, and Fe are included
* "t" files
    * Filenames must start with "t"
    * All elements with linear correlation with standard values (plus HG) are included

pXRF input data is processed in `df_measurements_with_standard_values`, attaching relevant standard values if present from `df_standards`.

In [12]:
xrf.df_input

                filename                                               text
0           t CC DEF.txt  SOURCE: t-0CC-1.csv\nKEY: 1.1.00001.1\nElement...
1         M PCAS DEF.txt  SOURCE: ISic002713-M-9.csv\nKEY: 1.1.00001.1\n...
2    t centuripe DEF.txt  SOURCE: ISic000655-t-a.csv\nKEY: 1.1.00001.1\n...
3           M CU DEF.txt  SOURCE: ISic000297-M-1.csv\nKEY: 1.1.00001.1\n...
4      t marsala DEF.txt  SOURCE: ISic000007-t-a.csv\nKEY: 1.1.00001.1\n...
5     t 20250612 DEF.txt  SOURCE: ISic000065-t-a.csv\nKEY: 1.1.00001.1\n...
6    MK taormina DEF.txt  SOURCE: ISic000662-MK-a.csv\nKEY: 1.1.00001.1\...
7    MK 20250612 DEF.txt  SOURCE: MK-ISic000065-a.csv\nKEY: 1.1.00001.1\...
8     t taormina DEF.txt  SOURCE: ISic000613-t-a.csv\nKEY: 1.1.00001.1\n...
9        t exmft DEF.txt  SOURCE: t-ISic000711-1.csv\nKEY: 1.1.00001.1\n...
10        t PCAS DEF.txt  SOURCE: ISic002713-t-9.csv\nKEY: 1.1.00001.1\n...
11     t termini DEF.txt  SOURCE: ISic000086-t-a.csv\nKEY: 1.1.00001.1\n...
12    MK salinas DEF.txt  SOURCE: ISic000003-MK-a.csv\nKEY: 1.1.00001.1\...
13          t CU DEF.txt  SOURCE: ISic000309-t-1.csv\nKEY: 1.1.00001.1\n...
14    MK tindari DEF.txt  SOURCE: ISic000672-MK-b.csv\nKEY: 1.1.00001.1\...
15     t halaesa DEF.txt  SOURCE: ISic000584-t-b.csv\nKEY: 1.1.00001.1\n...
16      MK exmft DEF.txt  SOURCE: MK-ISic000711-1.csv\nKEY: 1.1.00001.1\...
17    MK termini DEF.txt  SOURCE: ISic000086-MK-a.csv\nKEY: 1.1.00001.1\...
18       t MARPO DEF.txt  SOURCE: ISic000401-t-a.csv\nKEY: 1.1.00001.1\n...
19    MK marsala DEF.txt  SOURCE: ISic001661-MK-a.csv\nKEY: 1.1.00001.1\...
20         t CUb DEF.txt  SOURCE: ISic000297-t-1.csv\nKEY: 1.1.00001.1\n...
21    M 20250612 DEF.txt  SOURCE: ISic000896-M-1.csv\nKEY: 1.1.00001.1\n...
22  MK centuripe DEF.txt  SOURCE: ISic000655-t-a.csv\nKEY: 1.1.00001.1\n...
23         MK CC DEF.txt  SOURCE: 0-1.csv\nKEY: 1.1.00001.1\nElement  Gr...
24      MK MARPO DEF.txt  SOURCE: ISic001822-MK-6.csv\nKEY: 1.1.00001.1\...
25     t tindari DEF.txt  SOURCE: ISic000672-t-a.csv\nKEY: 1.1.00001.1\n...
26       MK PCAS DEF.txt  SOURCE: 0-1.csv\nKEY: 1.1.00001.1\nElement  Gr...
27    MK halaesa DEF.txt  SOURCE: ISic000584-MK-a.csv\nKEY: 1.1.00001.1\...
28     t salinas DEF.txt  SOURCE: ISic000003-t-a.csv\nKEY: 1.1.00001.1\n...

In [38]:
import re

from data.pXRF.pxrf_coefficients import calculate_corrected_value
import pandas as pd

df_corrected = pd.DataFrame()
df_corrected["ISic"] = ""

mk_elements = {
    "Si": "SiO2",
    "Ti": "TiO2",
    "Fe": "Fe2O3",
    "Mn": "MnO",
    "Ca": "CaO",
    "K": "K2O",
}
t_elements = [
    "Ti",
    "Fe",
    "Mn",
    "Ca",
    "K",
    "Ba",
    "Co",
    "Cr",
    "Ni",
    "Pb",
    "Rb",
    "Sr",
    "V",
    "Y",
    "Zn",
    "Zr",
    "Au",
    "Hg",
    "As",
    "Cu",
]
t_fe_output_elements = ["Fe2O3 (t)", "Fe (ppm)"]

txts = xrf.txt_input
for filename, txt in txts:
    is_mk = filename.startswith("M")

    for content in txt.split("\n\n"):
        lines = content.split("\n")

        source_name = lines[0].split(":")[-1].strip().split(".")[0].strip()

        has_isic = source_name.upper().startswith("ISIC")
        if has_isic:
            source_name = (
                source_name.replace("MK-", "").replace("M-", "").replace("t-", "")
            )

        if len(lines) < 3:
            continue

        header = lines[2].split()
        data = [ln.split() for ln in lines[3:]]

        df = pd.DataFrame(data, columns=header)
        df["Mass_fraction"] = df["Mass_fraction"].fillna(0).astype(float)

        if is_mk:
            df = df[df.Element.isin(mk_elements)]
            df = df.pivot_table(
                columns="Element", values="Mass_fraction", aggfunc="sum"
            ).reset_index(drop=True)

            df["total"] = df.sum(axis=1)
            df["errors"] = ""

            for element in mk_elements.keys():
                df[element] = df[element] / df["total"]
                df[element] = df[element].apply(
                    lambda x: calculate_corrected_value("MK", element, x)
                )
                df["errors"] = df.apply(
                    lambda x: f"{x['errors']} {x[element] if isinstance(x[element], str) else ''}",
                    axis=1,
                )
                df[element] = df[element].apply(
                    lambda x: None if isinstance(x, str) else x
                )

            df["total"] = df[mk_elements.keys()].sum(axis=1)

            for element, element_corrected in mk_elements.items():
                df[element_corrected] = df[element] / df["total"]

            df = df.drop(columns=list(mk_elements.keys()) + ["total"])
        else:
            df = df[df.Element.isin(t_elements)]
            df = df.pivot_table(
                columns="Element", values="Mass_fraction", aggfunc="sum"
            ).reset_index(drop=True)

            df["errors"] = ""

            for element in t_elements:
                elements = [element]
                if element == "Fe":
                    elements = t_fe_output_elements

                for element_corrected in elements:
                    # Check if element exists in df, if not save error in the corrected column
                    if element not in df.columns:
                        df[element_corrected] = (
                            f"Element {element} not found in {filename}/{source_name}"
                        )
                        continue

                    df[element_corrected] = df[element].apply(
                        lambda x: calculate_corrected_value("t", element_corrected, x)
                    )

                    # The calculate_corrected_value function now returns either a float or error string
                    # Check if any values are error strings and log them
                    error_values = df[element_corrected][
                        df[element_corrected].apply(
                            lambda x: isinstance(x, str) and "error" in x.lower()
                        )
                    ]

                    if not error_values.empty:
                        print(f"Errors found for {element_corrected}:")
                        for idx, error_msg in error_values.items():
                            print(f"  Row {idx}: {error_msg}")

        df["ISic"] = source_name
        # Check if the source name follows the format ISic\d{6}-\w+
        if not re.match(r"^ISic\d{6}-\w+$", source_name):
            df["errors"] = f"Invalid source name: {source_name}"

        df = df.reset_index(drop=True)
        df = df.rename(columns={"index": "Element"})
        df = df.set_index("ISic")

        df_corrected = df_corrected.combine_first(df)

# Remove the original Fe column it has been replaced by Fe2O3 in MK files,
# and Fe2O3 (t) and Fe (ppm) in t files
df_corrected = df_corrected.drop(columns=["Fe"])

# Merge rows with the same ISic
# df_corrected = df_corrected.groupby("ISic").agg("first")


df_corrected = df_corrected[
    [
        "errors",
        "SiO2",
        "TiO2",
        "Fe2O3",
        "MnO",
        "CaO",
        "K2O",
        "Ti",
        "Fe (ppm)",
        "Fe2O3 (t)",
        "Mn",
        "Ca",
        "K",
        "Ba",
        "Co",
        "Cr",
        "Ni",
        "Pb",
        "Rb",
        "Sr",
        "V",
        "Y",
        "Zn",
        "Zr",
        "Au",
        "Hg",
        "As",
        "Cu",
    ]
]
df_corrected = df_corrected.sort_index()
df_corrected.to_csv("../data/pXRF/output/corrected.csv")

df_corrected.head()

,errors,SiO2,TiO2,Fe2O3,MnO,CaO,K2O,Ti,Fe (ppm),Fe2O3 (t),Mn,Ca,K,Ba,Co,Cr,Ni,Pb,Rb,Sr,V,Y,Zn,Zr,Au,Hg,As,Cu
ISic,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0-1,Invalid source name: 0-1,0.997022,0.000017,0.000923,0.000009,0.000231,0.001798,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0-2,Invalid source name: 0-2,0.997076,0.000019,0.000915,0.000009,0.000222,0.001759,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0-3,Invalid source name: 0-3,0.99692,0.000019,0.00097,0.000009,0.000236,0.001845,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10-1,Invalid source name: 10-1,0.99559,0.000018,0.000969,0.000009,0.002004,0.00141,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10-2,Invalid source name: 10-2,0.995701,0.000020,0.00093,0.000009,0.001943,0.001397,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
# xrf.run(pivot_table=True)  # hide all cols besides Calc_fraction