In [1]:
import sys; sys.path.append('..')
from crossreads_petrography.xrd.utils import *
from crossreads_petrography.xrd.converter import *

In [2]:
xrd_converter = XRDConverter()

Initializing XRDConverter with input folder: /Users/ryan/github/crossreads-petrography/data/input/XRD @ 2024-07-16 19:14:10,401
Authenticating and accessing Google Spreadsheet @ 2024-07-16 19:14:10,401

In [3]:
df_xrd=xrd_converter.read_xrd_data()
df_meta=xrd_converter.read_crossreads_sheet()

Reading XRD data from /Users/ryan/github/crossreads-petrography/data/input/XRD @ 2024-07-16 19:14:11,157
Reading CrossReads sheet from Google Spreadsheet @ 2024-07-16 19:14:11,177
Read 151 rows from CrossReads sheet @ 2024-07-16 19:14:11,671

In [4]:
df=xrd_converter.get_updated_data()
df

Updating CrossReads sheet with XRD data @ 2024-07-16 19:14:13,115
Reading CrossReads sheet from Google Spreadsheet @ 2024-07-16 19:14:13,116
Read 151 rows from CrossReads sheet @ 2024-07-16 19:14:13,615
[ISic000104] XRD other minerals: "" -> "Qcalcitmg"  @ 2024-07-16 19:14:13,619
[ISic000004] XRD other minerals: "" -> "Qcalcitmg"  @ 2024-07-16 19:14:13,620
[ISic000034] XRD calcite content (%) ESD: "1" -> "1.0"  @ 2024-07-16 19:14:13,620
[ISic000034] XRD other minerals: "" -> "Qcalcitmg"  @ 2024-07-16 19:14:13,621
[ISic000036] XRD other minerals: "" -> "Qcalcitmg"  @ 2024-07-16 19:14:13,622
[ISic000068] XRD calcite content (%): "0" -> "0.0"  @ 2024-07-16 19:14:13,622
[ISic000068] XRD calcite content (%) ESD: "0" -> "0.0"  @ 2024-07-16 19:14:13,623
[ISic000068] XRD other minerals: " QIron Qgypsum QNa2SO14H20" -> "QIron; QNa2SO14H20; Qcalcitmg; Qgypsum"  @ 2024-07-16 19:14:13,623
[ISic000069] XRD other minerals: " Qquartz QIron" -> "QIron; Qquartz"  @ 2024-07-16 19:14:13,624
[ISic000121] XRD calcite content (%): "0" -> "0.0"  @ 2024-07-16 19:14:13,624
[ISic000121] XRD calcite content (%) ESD: "0" -> "0.0"  @ 2024-07-16 19:14:13,625
[ISic000121] XRD dolomite content (%): "1" -> "1.0"  @ 2024-07-16 19:14:13,626
[ISic000121] XRD other minerals: " QIron" -> "QIron; Qcalcitmg"  @ 2024-07-16 19:14:13,627
[ISic000148] XRD other minerals: " QSiO2p3221" -> "QSiO2p3221; Qcalcitmg"  @ 2024-07-16 19:14:13,627
[ISic000163] XRD other minerals: "" -> "Qcalcitmg"  @ 2024-07-16 19:14:13,628
[ISic000178] XRD other minerals: " Qorthoclase" -> "Qcalcitmg; Qorthoclase"  @ 2024-07-16 19:14:13,629
[ISic000207] XRD other minerals: "" -> "Qcalcitmg"  @ 2024-07-16 19:14:13,630
[ISic000220] XRD other minerals: "" -> "Qcalcitmg"  @ 2024-07-16 19:14:13,631
[ISic000227] XRD other minerals: "" -> "Qcalcitmg"  @ 2024-07-16 19:14:13,632
[ISic000229] XRD other minerals: "" -> "Qcalcitmg"  @ 2024-07-16 19:14:13,632
[ISic000232] XRD other minerals: "" -> "Qcalcitmg"  @ 2024-07-16 19:14:13,633
[ISic000579] XRD other minerals: " Qmicroint2" -> "Qcalcitmg; Qmicroint2"  @ 2024-07-16 19:14:13,634
[ISic000871] XRD other minerals: " QMirabilite Qironalpha" -> "QMirabilite; Qcalcitmg; Qironalpha"  @ 2024-07-16 19:14:13,635
[ISic001120] XRD other minerals: "" -> "Qcalcitmg"  @ 2024-07-16 19:14:13,635
[ISic001135] XRD other minerals: "" -> "Qcalcitmg"  @ 2024-07-16 19:14:13,636
[ISic003335] XRD other minerals: "" -> "Qcalcitmg"  @ 2024-07-16 19:14:13,636
[ISic004341] XRD other minerals: " QIron" -> "QIron; Qcalcitmg"  @ 2024-07-16 19:14:13,637
[ISic004363] XRD calcite content (%): "10" -> "10.0"  @ 2024-07-16 19:14:13,637
[ISic004363] XRD calcite content (%) ESD: "48" -> "48.0"  @ 2024-07-16 19:14:13,638
[ISic004363] XRD other minerals: " QIron" -> "QIron; Qcalcitmg"  @ 2024-07-16 19:14:13,638
[ISic004364] XRD other minerals: "" -> "Qcalcitmg"  @ 2024-07-16 19:14:13,639
[ISic004365] XRD calcite content (%): "0" -> "0.0"  @ 2024-07-16 19:14:13,639
[ISic004365] XRD calcite content (%) ESD: "0" -> "0.0"  @ 2024-07-16 19:14:13,640
[ISic004365] XRD other minerals: " QIron" -> "QIron; Qcalcitmg"  @ 2024-07-16 19:14:13,640
Adding 26 new rows: ISic000097p, ISic001399-1, tao100, tao105, tao106, tao227, tao240, tao31, tao5, tao57, tao60, tao63, tao64, tao64bis, tao67, tao67malta, tao69, tao7, tao74, tao87, tao90, taoLastraR, taoPiedi, taoSarcofago, taomascherome, taoreclinato @ 2024-07-16 19:14:13,641
Calculating combined columns @ 2024-07-16 19:14:13,642
Calculated XRD clay minerals, K-feldspar, and plagioclase columns @ 2024-07-16 19:14:13,657

,entity type,rock type,rock desc1,rock desc2,visually assessed granulometry (very fine < 1mm; fine < 2mm; medium 2-5mm; coarse > 5mm),visually assessed colour,visually assessed sharpness of veins,visually assessed colour of veins,visually assessed protolith features,visually assessed monomineralic,...,EPR dolomite %,EPR width ave,EPR width stdevp,EPR g=2.0044 ave,EPR g=2.0044 stdevp,EPR g=14.2515 ave,EPR g=14.2515 stdevp,XRD clay minerals,XRD K-feldspar,XRD plagioclase
reference or rock id,,,,,,,,,,,,,,,,,,,,,
Capedri et al 2004,reference,marble,carrara,,,,,,,,...,,,,,,,,0,0,0
Antonelli and Nestola 2021,reference,marble,carrara,,very fine,white/whitish,edgeless veins,grey to black,,,...,,,,,,,,0,0,0
Antonelli and Nestola 2021,reference,marble,göktepe,,very fine,white/whitish,,,,,...,,,,,,,,0,0,0
Antonelli and Lazzarini 2015,reference,marble,carrara,"fantiscritti, ravaccione, fossacava",very fine,white/whitish,edgeless and sharp veins,grey to black,no,yes,...,,,,,,,,0,0,0
Antonelli and Lazzarini 2015,reference,marble,paros-1,lychnites - stephani (marathi),fine,white/whitish,,,no,yes,...,,,,,,,,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
taoLastraR,,,,,,,,,,,...,,,,,,,,0,0,0
taoPiedi,,,,,,,,,,,...,,,,,,,,0,0,0
taoSarcofago,,,,,,,,,,,...,,,,,,,,0,0,0
taomascherome,,,,,,,,,,,...,,,,,,,,0,0,0
taoreclinato,,,,,,,,,,,...,,,,,,,,0,0,0

In [ ]:
self = xrd_converter
xrd_data = self.read_xrd_data()
crossreads_data = self.read_crossreads_sheet()
updated_data = self.update_crossreads_sheet(xrd_data, crossreads_data)
updated_data = self.calculate_combined_columns(updated_data)

2024-07-16 18:47:33.513 | INFO     | crossreads_petrography.xrd.converter:read_crossreads_sheet:73 - Reading CrossReads sheet from Google Spreadsheet
2024-07-16 18:47:34.159 | DEBUG    | crossreads_petrography.xrd.converter:read_crossreads_sheet:88 - Read 151 rows from CrossReads sheet
2024-07-16 18:47:34.160 | INFO     | crossreads_petrography.xrd.converter:get_updated_crossreads_sheet:177 - Updating CrossReads sheet with XRD data
2024-07-16 18:47:34.163 | INFO     | crossreads_petrography.xrd.converter:get_updated_crossreads_sheet:191 - [ISic000104] XRD other minerals:  -> Qcalcitmg
2024-07-16 18:47:34.165 | INFO     | crossreads_petrography.xrd.converter:get_updated_crossreads_sheet:191 - [ISic000004] XRD other minerals:  -> Qcalcitmg
2024-07-16 18:47:34.165 | INFO     | crossreads_petrography.xrd.converter:get_updated_crossreads_sheet:191 - [ISic000034] XRD calcite content (%) ESD: 1 -> 1.0
2024-07-16 18:47:34.166 | INFO     | crossreads_petrography.xrd.converter:get_updated_crossreads_sheet:191 - [ISic000034] XRD other minerals:  -> Qcalcitmg
2024-07-16 18:47:34.167 | INFO     | crossreads_petrography.xrd.converter:get_updated_crossreads_sheet:191 - [ISic000036] XRD other minerals:  -> Qcalcitmg
2024-07-16 18:47:34.168 | INFO     | crossreads_petrography.xrd.converter:get_updated_crossreads_sheet:191 - [ISic000068] XRD calcite content (%): 0 -> 0.0
2024-07-16 18:47:34.169 | INFO     | crossreads_petrography.xrd.converter:get_updated_crossreads_sheet:191 - [ISic000068] XRD calcite content (%) ESD: 0 -> 0.0
2024-07-16 18:47:34.169 | INFO     | crossreads_petrography.xrd.converter:get_updated_crossreads_sheet:191 - [ISic000068] XRD other minerals:  QIron Qgypsum QNa2SO14H20 -> QIron; QNa2SO14H20; Qcalcitmg; Qgypsum
2024-07-16 18:47:34.170 | INFO     | crossreads_petrography.xrd.converter:get_updated_crossreads_sheet:191 - [ISic000069] XRD other minerals:  Qquartz QIron -> QIron; Qquartz
2024-07-16 18:47:34.170 | INFO     | crossreads_petrography.xrd.converter:get_updated_crossreads_sheet:191 - [ISic000121] XRD calcite content (%): 0 -> 0.0
2024-07-16 18:47:34.171 | INFO     | crossreads_petrography.xrd.converter:get_updated_crossreads_sheet:191 - [ISic000121] XRD calcite content (%) ESD: 0 -> 0.0
2024-07-16 18:47:34.172 | INFO     | crossreads_petrography.xrd.converter:get_updated_crossreads_sheet:191 - [ISic000121] XRD dolomite content (%): 1 -> 1.0
2024-07-16 18:47:34.172 | INFO     | crossreads_petrography.xrd.converter:get_updated_crossreads_sheet:191 - [ISic000121] XRD other minerals:  QIron -> QIron; Qcalcitmg
2024-07-16 18:47:34.173 | INFO     | crossreads_petrography.xrd.converter:get_updated_crossreads_sheet:191 - [ISic000148] XRD other minerals:  QSiO2p3221 -> QSiO2p3221; Qcalcitmg
2024-07-16 18:47:34.174 | INFO     | crossreads_petrography.xrd.converter:get_updated_crossreads_sheet:191 - [ISic000163] XRD other minerals:  -> Qcalcitmg
2024-07-16 18:47:34.175 | INFO     | crossreads_petrography.xrd.converter:get_updated_crossreads_sheet:191 - [ISic000178] XRD other minerals:  Qorthoclase -> Qcalcitmg; Qorthoclase
2024-07-16 18:47:34.176 | INFO     | crossreads_petrography.xrd.converter:get_updated_crossreads_sheet:191 - [ISic000207] XRD other minerals:  -> Qcalcitmg
2024-07-16 18:47:34.176 | INFO     | crossreads_petrography.xrd.converter:get_updated_crossreads_sheet:191 - [ISic000220] XRD other minerals:  -> Qcalcitmg
2024-07-16 18:47:34.177 | INFO     | crossreads_petrography.xrd.converter:get_updated_crossreads_sheet:191 - [ISic000227] XRD other minerals:  -> Qcalcitmg
2024-07-16 18:47:34.178 | INFO     | crossreads_petrography.xrd.converter:get_updated_crossreads_sheet:191 - [ISic000229] XRD other minerals:  -> Qcalcitmg
2024-07-16 18:47:34.179 | INFO     | crossreads_petrography.xrd.converter:get_updated_crossreads_sheet:191 - [ISic000232] XRD other minerals:  -> Qcalcitmg
2024-07-16 18:47:34.180 | INFO     | crossreads_petrography.xrd.converter:get_updated_crossreads_sheet:191 - [ISic000579] XRD other minerals:  Qmicroint2 -> Qcalcitmg; Qmicroint2
2024-07-16 18:47:34.181 | INFO     | crossreads_petrography.xrd.converter:get_updated_crossreads_sheet:191 - [ISic000871] XRD other minerals:  QMirabilite Qironalpha -> QMirabilite; Qcalcitmg; Qironalpha
2024-07-16 18:47:34.182 | INFO     | crossreads_petrography.xrd.converter:get_updated_crossreads_sheet:191 - [ISic001120] XRD other minerals:  -> Qcalcitmg
2024-07-16 18:47:34.182 | INFO     | crossreads_petrography.xrd.converter:get_updated_crossreads_sheet:191 - [ISic001135] XRD other minerals:  -> Qcalcitmg
2024-07-16 18:47:34.183 | INFO     | crossreads_petrography.xrd.converter:get_updated_crossreads_sheet:191 - [ISic003335] XRD other minerals:  -> Qcalcitmg
2024-07-16 18:47:34.183 | INFO     | crossreads_petrography.xrd.converter:get_updated_crossreads_sheet:191 - [ISic004341] XRD other minerals:  QIron -> QIron; Qcalcitmg
2024-07-16 18:47:34.184 | INFO     | crossreads_petrography.xrd.converter:get_updated_crossreads_sheet:191 - [ISic004363] XRD calcite content (%): 10 -> 10.0
2024-07-16 18:47:34.184 | INFO     | crossreads_petrography.xrd.converter:get_updated_crossreads_sheet:191 - [ISic004363] XRD calcite content (%) ESD: 48 -> 48.0
2024-07-16 18:47:34.185 | INFO     | crossreads_petrography.xrd.converter:get_updated_crossreads_sheet:191 - [ISic004363] XRD other minerals:  QIron -> QIron; Qcalcitmg
2024-07-16 18:47:34.185 | INFO     | crossreads_petrography.xrd.converter:get_updated_crossreads_sheet:191 - [ISic004364] XRD other minerals:  -> Qcalcitmg
2024-07-16 18:47:34.186 | INFO     | crossreads_petrography.xrd.converter:get_updated_crossreads_sheet:191 - [ISic004365] XRD calcite content (%): 0 -> 0.0
2024-07-16 18:47:34.186 | INFO     | crossreads_petrography.xrd.converter:get_updated_crossreads_sheet:191 - [ISic004365] XRD calcite content (%) ESD: 0 -> 0.0
2024-07-16 18:47:34.187 | INFO     | crossreads_petrography.xrd.converter:get_updated_crossreads_sheet:191 - [ISic004365] XRD other minerals:  QIron -> QIron; Qcalcitmg
2024-07-16 18:47:34.187 | INFO     | crossreads_petrography.xrd.converter:get_updated_crossreads_sheet:196 - Adding 26 new rows: ISic000097p, ISic001399-1, tao100, tao105, tao106, tao227, tao240, tao31, tao5, tao57, tao60, tao63, tao64, tao64bis, tao67, tao67malta, tao69, tao7, tao74, tao87, tao90, taoLastraR, taoPiedi, taoSarcofago, taomascherome, taoreclinato
2024-07-16 18:47:34.191 | INFO     | crossreads_petrography.xrd.converter:calculate_combined_columns:95 - Calculating combined columns
2024-07-16 18:47:34.203 | DEBUG    | crossreads_petrography.xrd.converter:calculate_combined_columns:105 - Calculated XRD clay minerals, K-feldspar, and plagioclase columns

In [ ]:
updated_data

,entity type,rock type,rock desc1,rock desc2,visually assessed granulometry (very fine < 1mm; fine < 2mm; medium 2-5mm; coarse > 5mm),visually assessed colour,visually assessed sharpness of veins,visually assessed colour of veins,visually assessed protolith features,visually assessed monomineralic,...,EPR dolomite %,EPR width ave,EPR width stdevp,EPR g=2.0044 ave,EPR g=2.0044 stdevp,EPR g=14.2515 ave,EPR g=14.2515 stdevp,XRD clay minerals,XRD K-feldspar,XRD plagioclase
reference or rock id,,,,,,,,,,,,,,,,,,,,,
Capedri et al 2004,reference,marble,carrara,,,,,,,,...,,,,,,,,0,0,0
Antonelli and Nestola 2021,reference,marble,carrara,,very fine,white/whitish,edgeless veins,grey to black,,,...,,,,,,,,0,0,0
Antonelli and Nestola 2021,reference,marble,göktepe,,very fine,white/whitish,,,,,...,,,,,,,,0,0,0
Antonelli and Lazzarini 2015,reference,marble,carrara,"fantiscritti, ravaccione, fossacava",very fine,white/whitish,edgeless and sharp veins,grey to black,no,yes,...,,,,,,,,0,0,0
Antonelli and Lazzarini 2015,reference,marble,paros-1,lychnites - stephani (marathi),fine,white/whitish,,,no,yes,...,,,,,,,,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
taoLastraR,,,,,,,,,,,...,,,,,,,,0,0,0
taoPiedi,,,,,,,,,,,...,,,,,,,,0,0,0
taoSarcofago,,,,,,,,,,,...,,,,,,,,0,0,0
taomascherome,,,,,,,,,,,...,,,,,,,,0,0,0
taoreclinato,,,,,,,,,,,...,,,,,,,,0,0,0

In [ ]:
def get_updated_crossreads_sheet(df_xrd, df_meta):
    logger.info("Updating CrossReads sheet with XRD data")
    
    # Create a new dataframe with all columns from both df_meta and df_xrd
    cols = list(df_meta.columns) + [c for c in df_xrd if c not in set(df_meta.columns)]
    df_combined = df_meta.reindex(columns=cols)
    
    # Update common columns for existing rows
    df_combined.update(df_xrd)
    
    # Add new rows from df_xrd that don't exist in df_meta
    new_rows = df_xrd.loc[~df_xrd.index.isin(df_meta.index)]
    df_combined = pd.concat([df_combined, new_rows])
    
    # Fill NaN with empty string
    return df_combined.fillna('').rename_axis(df_meta.index.name)

In [ ]:
xrd_update_crossreads_sheet(df_xrd, df_meta)

NameError: name 'xrd_update_crossreads_sheet' is not defined

2024-07-16 17:53:24.801 | INFO     | crossreads_petrography.xrd.converter:update_crossreads_sheet:76 - Updating CrossReads sheet with XRD data
2024-07-16 17:53:24.807 | INFO     | crossreads_petrography.xrd.converter:update_crossreads_sheet:90 - Added 26 new samples

ValueError: cannot reindex on an axis with duplicate labels

In [ ]:
import numpy as np
np.nan - 28

nan