In [1]:
import sys; sys.path.append('..')
from crossreads_petrography import *

Loading config from /Users/ryan/github/crossreads-petrography/notebooks/../data/default_config.yaml

In [7]:
xrd_converter = XRDConverter()
xrd_converter.paths

{'xrd': '/Users/ryan/github/crossreads-petrography/data/XRD',
 'input': '/Users/ryan/github/crossreads-petrography/data/XRD/input',
 'mineral_types': '/Users/ryan/github/crossreads-petrography/data/XRD/Mineral Categories.xlsx',
 'output': '/Users/ryan/github/crossreads-petrography/data/XRD/output'}

In [10]:
df=read_path('xrd.mineral_types')
df[df.subtype.str.lower().str.contains('calc')]

       subtype                            colname category
22    Qcalcite            XRD calcite content (%)      NaN
23   Qcalcitmg            XRD calcite content (%)      NaN
47  QMgCalcite  XRD magnesian calcite content (%)      NaN

In [11]:
pd.options.display.max_colwidth = None

In [12]:
xrd_converter.df_input[['File']].sample(n=10)

                                                                                                                   File
117                                                                    E:/nextcloud/ISicily/petrography/XRD/000184p.lst
136                                                         C:/Users/Alessia/Dropbox/Taormina Mostra/XRD/xrd/tao100.lst
91   C:/Users/Alessia/OneDrive - Nexus365/oxford/inart2024/XRD/marblesXRD-ISic-KDL_PM/marblesXRD-ISic-KDL_PM/000220.lst
80                                                                    E:/nextcloud/ISicily/petrography/XRD/003370vg.lst
60                                                                      E:/nextcloud/ISicily/petrography/XRD/001134.lst
20                                                                   E:/nextcloud/ISicily/petrography/XRD/001108pvg.lst
51                                                           C:/Users/Alessia/Dropbox/Taormina Mostra/XRD/xrd/tao63.lst
36                                                                 E:/nextcloud/ISicily/petrography/XRD/000131light.lst
172                                                         C:/Users/Alessia/Dropbox/Taormina Mostra/XRD/xrd/tao240.lst
79                                                                   E:/nextcloud/ISicily/petrography/XRD/001138pvg.lst

In [16]:
xrd_converter.df_reformatted

ESD (94.0) is larger than value (1.0) for ISic003373vg on qcalcite
ESD (1.3) is larger than value (0.0) for ISic003373vg on qquartz
ESD (96.0) is larger than value (0.0) for ISic003373vg on qchloritfxbg
ESD (0.0028) is larger than value (0.0016) for tao31 on qmusc2m1
ESD (0.00062) is larger than value (0.00025) for taoPiedi on qsio2p3121
ESD (0.76) is larger than value (0.54) for ISic001138pvg on qcalcite
ESD (0.024) is larger than value (0.017) for ISic001138pvg on qmusc2m1
ESD (0.91) is larger than value (0.36) for ISic001138pvg on qkaolinitedis
ESD (0.006) is larger than value (0.0042) for ISic001138pvg on qhematite
ESD (0.06) is larger than value (0.042) for ISic001138pvg on qchlorite2b
ESD (0.017) is larger than value (0.012) for ISic001138pvg on qquartz
ESD (0.024) is larger than value (0.017) for ISic001138pvg on qalbite
ESD (0.0048) is larger than value (0.0034) for ISic001138pvg on qenstatitemg06fe04ca
ESD (0.0089) is larger than value (0.0061) for ISic001138pvg on qenstatite
ESD (0.00047) is larger than value (0.00032) for ISic001138pvg on qsylvite
ESD (0.88) is larger than value (0.87) for ISic000068 on qcalcitmg
ESD (0.013) is larger than value (0.012) for ISic000068 on qdolomite
ESD (0.97) is larger than value (0.04) for ISic000068 on qiron
ESD (0.025) is larger than value (0.024) for ISic000068 on qgypsum
ESD (0.077) is larger than value (0.045) for ISic000163 on qcalcitmg
ESD (0.0021) is larger than value (0.0012) for ISic000163 on qdolomite
ESD (0.48) is larger than value (0.1) for ISic004363 on qcalcite
ESD (3.6) is larger than value (0.8) for ISic004363 on qcalcitmg
ESD (0.065) is larger than value (0.014) for ISic004363 on qdolomite
ESD (4.2) is larger than value (0.1) for ISic004363 on qiron

,XRD calcite content (%),XRD calcite content (%) ESD,XRD quartz content (%),XRD quartz content (%) ESD,XRD microcline content (%),XRD microcline content (%) ESD,XRD muscovite content (%),XRD muscovite content (%) ESD,XRD chlorite content (%),XRD chlorite content (%) ESD,...,XRD Fe-oxihydroxides content (%) ESD,XRD K-sanidine content (%),XRD K-sanidine content (%) ESD,XRD Na-sanidine content (%),XRD Na-sanidine content (%) ESD,XRD kaolinite content (%),XRD kaolinite content (%) ESD,XRD andesine content (%),XRD andesine content (%) ESD,XRD other minerals
Sample,,,,,,,,,,,,,,,,,,,,,
ISic000004,96.39,0.87,,,,,,,,,...,,,,,,,,,,
ISic000009grey,100.0,0.0,,,,,,,,,...,,,,,,,,,,
ISic000009pink,87.45,0.38,,,,,,,,,...,,,,,,8.24,0.33,,,Qcerussite; Qhydrotalcite
ISic000015,100.0,0.0,,,,,,,,,...,,,,,,,,,,
ISic000017,100.0,0.0,,,,,,,,,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
taoLastraR,99.6,0.11,0.0,0.0,,,0.225,0.074,,,...,,,,,,,,,,
taoPiedi,88.05,0.22,0.025,0.062,,,0.59,0.15,,,...,,,,,,,,,,
taoSarcofago,98.96,0.16,0.242,0.048,,,0.35,0.11,,,...,,,,,,,,,,
taomascherome,99.22,0.37,0.13,0.13,,,0.0,0.0,,,...,,,,,,,,,,
taoreclinato,99.591,0.084,0.07,0.021,,,0.0,0.0,,,...,,,,,,,,,,

In [17]:
samples = xrd_converter.df_output.index
'ISic000097p' in samples

ESD (94.0) is larger than value (1.0) for ISic003373vg on qcalcite
ESD (1.3) is larger than value (0.0) for ISic003373vg on qquartz
ESD (96.0) is larger than value (0.0) for ISic003373vg on qchloritfxbg
ESD (0.0028) is larger than value (0.0016) for tao31 on qmusc2m1
ESD (0.00062) is larger than value (0.00025) for taoPiedi on qsio2p3121
ESD (0.76) is larger than value (0.54) for ISic001138pvg on qcalcite
ESD (0.024) is larger than value (0.017) for ISic001138pvg on qmusc2m1
ESD (0.91) is larger than value (0.36) for ISic001138pvg on qkaolinitedis
ESD (0.006) is larger than value (0.0042) for ISic001138pvg on qhematite
ESD (0.06) is larger than value (0.042) for ISic001138pvg on qchlorite2b
ESD (0.017) is larger than value (0.012) for ISic001138pvg on qquartz
ESD (0.024) is larger than value (0.017) for ISic001138pvg on qalbite
ESD (0.0048) is larger than value (0.0034) for ISic001138pvg on qenstatitemg06fe04ca
ESD (0.0089) is larger than value (0.0061) for ISic001138pvg on qenstatite
ESD (0.00047) is larger than value (0.00032) for ISic001138pvg on qsylvite
ESD (0.88) is larger than value (0.87) for ISic000068 on qcalcitmg
ESD (0.013) is larger than value (0.012) for ISic000068 on qdolomite
ESD (0.97) is larger than value (0.04) for ISic000068 on qiron
ESD (0.025) is larger than value (0.024) for ISic000068 on qgypsum
ESD (0.077) is larger than value (0.045) for ISic000163 on qcalcitmg
ESD (0.0021) is larger than value (0.0012) for ISic000163 on qdolomite
ESD (0.48) is larger than value (0.1) for ISic004363 on qcalcite
ESD (3.6) is larger than value (0.8) for ISic004363 on qcalcitmg
ESD (0.065) is larger than value (0.014) for ISic004363 on qdolomite
ESD (4.2) is larger than value (0.1) for ISic004363 on qiron

True

In [18]:
xrd_converter.df_mineral_types

              subtype                      colname      category
0                   *           XRD other minerals
1             QALBINT       XRD albite content (%)   Plagioclase
2             Qalbint       XRD albite content (%)   Plagioclase
3             QAlbite       XRD albite content (%)   Plagioclase
4           QAnalbite       XRD albite content (%)   Plagioclase
..                ...                          ...           ...
82          QSanina75  XRD Na-sanidine content (%)
83          QSANINA85  XRD Na-sanidine content (%)
84         QSiO2p3121       XRD quartz content (%)
85         QSiO2p3221       XRD quartz content (%)
86  Qsmectitedi2wfix1     XRD smectite content (%)  Clay Mineral

[87 rows x 3 columns]

In [20]:
xrd_converter.df_output.loc['ISic000097p']

ESD (94.0) is larger than value (1.0) for ISic003373vg on qcalcite
ESD (1.3) is larger than value (0.0) for ISic003373vg on qquartz
ESD (96.0) is larger than value (0.0) for ISic003373vg on qchloritfxbg
ESD (0.0028) is larger than value (0.0016) for tao31 on qmusc2m1
ESD (0.00062) is larger than value (0.00025) for taoPiedi on qsio2p3121
ESD (0.76) is larger than value (0.54) for ISic001138pvg on qcalcite
ESD (0.024) is larger than value (0.017) for ISic001138pvg on qmusc2m1
ESD (0.91) is larger than value (0.36) for ISic001138pvg on qkaolinitedis
ESD (0.006) is larger than value (0.0042) for ISic001138pvg on qhematite
ESD (0.06) is larger than value (0.042) for ISic001138pvg on qchlorite2b
ESD (0.017) is larger than value (0.012) for ISic001138pvg on qquartz
ESD (0.024) is larger than value (0.017) for ISic001138pvg on qalbite
ESD (0.0048) is larger than value (0.0034) for ISic001138pvg on qenstatitemg06fe04ca
ESD (0.0089) is larger than value (0.0061) for ISic001138pvg on qenstatite
ESD (0.00047) is larger than value (0.00032) for ISic001138pvg on qsylvite
ESD (0.88) is larger than value (0.87) for ISic000068 on qcalcitmg
ESD (0.013) is larger than value (0.012) for ISic000068 on qdolomite
ESD (0.97) is larger than value (0.04) for ISic000068 on qiron
ESD (0.025) is larger than value (0.024) for ISic000068 on qgypsum
ESD (0.077) is larger than value (0.045) for ISic000163 on qcalcitmg
ESD (0.0021) is larger than value (0.0012) for ISic000163 on qdolomite
ESD (0.48) is larger than value (0.1) for ISic004363 on qcalcite
ESD (3.6) is larger than value (0.8) for ISic004363 on qcalcitmg
ESD (0.065) is larger than value (0.014) for ISic004363 on qdolomite
ESD (4.2) is larger than value (0.1) for ISic004363 on qiron

XRD calcite content (%)                  97.46
XRD calcite content (%) ESD                0.8
XRD quartz content (%)
XRD quartz content (%) ESD
XRD microcline content (%)
XRD microcline content (%) ESD
XRD muscovite content (%)
XRD muscovite content (%) ESD
XRD chlorite content (%)
XRD chlorite content (%) ESD
XRD albite content (%)
XRD albite content (%) ESD
XRD orthoclase content (%)
XRD orthoclase content (%) ESD
XRD oligoclase content (%)
XRD oligoclase content (%) ESD
XRD anorthite content (%)
XRD anorthite content (%) ESD
XRD aragonite content (%)
XRD aragonite content (%) ESD
XRD dolomite content (%)                  2.54
XRD dolomite content (%) ESD              0.29
XRD magnesian calcite content (%)
XRD magnesian calcite content (%) ESD
XRD gypsum content (%)
XRD gypsum content (%) ESD
XRD Fe-oxihydroxides content (%)
XRD Fe-oxihydroxides content (%) ESD
XRD K-sanidine content (%)
XRD K-sanidine content (%) ESD
XRD Na-sanidine content (%)
XRD Na-sanidine content (%) ESD
XRD kaolinite content (%)
XRD kaolinite content (%) ESD
XRD andesine content (%)
XRD andesine content (%) ESD
XRD other minerals
XRD Clay Mineral                           0.0
XRD K_Feldspar                             0.0
XRD Plagioclase                            0.0
XRD Sulphates                              0.0
Name: ISic000097p, dtype: object

In [ ]:
xrd_converter.run()

Postprocessing XRD data @ 2024-08-26 18:21:17,126
Saved: xrd_data_postprocessed.xlsx @ 2024-08-26 18:21:17,200