In [1]:
import sys; sys.path.append('..')
from crossreads_petrography import *

Loading config from /Users/ryan/github/crossreads-petrography/notebooks/../data/default_config.yaml

In [13]:
xrd_converter = XRDConverter()

In [14]:
xrd_converter.df_input

,File,Sample,Sample ID,"Parameter, Goal",Value,ESD
0,E:/nextcloud/ISicily/petrography/XRD/001207vg.lst,001207vg,,QCalcite,0.00441,"0.00085,"
1,E:/nextcloud/ISicily/petrography/XRD/001207vg.lst,001207vg,,Qquartz,0.40860,"0.0033,"
2,E:/nextcloud/ISicily/petrography/XRD/001207vg.lst,001207vg,,Qmicroint2,0.09400,"0.0025,"
3,E:/nextcloud/ISicily/petrography/XRD/001207vg.lst,001207vg,,Qmusc2m1,0.13600,"0.0044,"
4,E:/nextcloud/ISicily/petrography/XRD/001207vg.lst,001207vg,,Qchlorite2b,0.05540,"0.0023,"
...,...,...,...,...,...,...
201,C:/Users/Alessia/OneDrive - Nexus365/oxford/in...,004365,,QIron,0.05320,0.0022
202,C:/Users/Alessia/OneDrive - Nexus365/oxford/in...,004365,,Rwp,11.80000,
203,C:/Users/Alessia/OneDrive - Nexus365/oxford/in...,004365,,Rexp,11.65000,
204,C:/Users/Alessia/OneDrive - Nexus365/oxford/in...,004365,,Chi2,1.02590,
205,C:/Users/Alessia/OneDrive - Nexus365/oxford/in...,004365,,GOF,1.01290,

In [15]:
xrd_converter.df_mineral_types

              subtype                      colname      category
0                   *           XRD other minerals
1             QALBINT       XRD albite content (%)   Plagioclase
2             Qalbint       XRD albite content (%)
3             QAlbite       XRD albite content (%)   Plagioclase
4           QAnalbite       XRD albite content (%)   Plagioclase
..                ...                          ...           ...
82          QSanina75  XRD Na-sanidine content (%)
83          QSANINA85  XRD Na-sanidine content (%)
84         QSiO2p3121       XRD quartz content (%)
85         QSiO2p3221       XRD quartz content (%)
86  Qsmectitedi2wfix1     XRD smectite content (%)  Clay Mineral

[87 rows x 3 columns]

In [16]:
xrd_converter.df_params

                                       colname      category
subtype
*                           XRD other minerals
qalbint                 XRD albite content (%)   Plagioclase
qalbite                 XRD albite content (%)   Plagioclase
qanalbite               XRD albite content (%)   Plagioclase
qandesine_1           XRD andesine content (%)   Plagioclase
...                                        ...           ...
qsanina75          XRD Na-sanidine content (%)
qsanina85          XRD Na-sanidine content (%)
qsio2p3121              XRD quartz content (%)
qsio2p3221              XRD quartz content (%)
qsmectitedi2wfix1     XRD smectite content (%)  Clay Mineral

[82 rows x 2 columns]

In [17]:
xrd_converter.df_preproc

ESD (94.0) is larger than value (1.0) for ISic003373vg on qcalcite
ESD (1.3) is larger than value (0.0) for ISic003373vg on qquartz
ESD (96.0) is larger than value (0.0) for ISic003373vg on qchloritfxbg
ESD (0.0028) is larger than value (0.0016) for tao31 on qmusc2m1
ESD (0.00062) is larger than value (0.00025) for taoPiedi on qsio2p3121
ESD (0.76) is larger than value (0.54) for ISic001138pvg on qcalcite
ESD (0.024) is larger than value (0.017) for ISic001138pvg on qmusc2m1
ESD (0.91) is larger than value (0.36) for ISic001138pvg on qkaolinitedis
ESD (0.006) is larger than value (0.0042) for ISic001138pvg on qhematite
ESD (0.06) is larger than value (0.042) for ISic001138pvg on qchlorite2b
ESD (0.017) is larger than value (0.012) for ISic001138pvg on qquartz
ESD (0.024) is larger than value (0.017) for ISic001138pvg on qalbite
ESD (0.0048) is larger than value (0.0034) for ISic001138pvg on qenstatitemg06fe04ca
ESD (0.0089) is larger than value (0.0061) for ISic001138pvg on qenstatite
ESD (0.00047) is larger than value (0.00032) for ISic001138pvg on qsylvite
ESD (0.88) is larger than value (0.87) for ISic000068 on qcalcitmg
ESD (0.013) is larger than value (0.012) for ISic000068 on qdolomite
ESD (0.97) is larger than value (0.04) for ISic000068 on qiron
ESD (0.025) is larger than value (0.024) for ISic000068 on qgypsum
ESD (0.077) is larger than value (0.045) for ISic000163 on qcalcitmg
ESD (0.0021) is larger than value (0.0012) for ISic000163 on qdolomite
ESD (0.48) is larger than value (0.1) for ISic004363 on qcalcite
ESD (3.6) is larger than value (0.8) for ISic004363 on qcalcitmg
ESD (0.065) is larger than value (0.014) for ISic004363 on qdolomite
ESD (4.2) is larger than value (0.1) for ISic004363 on qiron

,XRD calcite content (%),XRD calcite content (%) ESD,XRD quartz content (%),XRD quartz content (%) ESD,XRD microcline content (%),XRD microcline content (%) ESD,XRD muscovite content (%),XRD muscovite content (%) ESD,XRD chlorite content (%),XRD chlorite content (%) ESD,...,XRD Fe-oxihydroxides content (%) ESD,XRD K-sanidine content (%),XRD K-sanidine content (%) ESD,XRD Na-sanidine content (%),XRD Na-sanidine content (%) ESD,XRD kaolinite content (%),XRD kaolinite content (%) ESD,XRD andesine content (%),XRD andesine content (%) ESD,XRD other minerals
Sample,,,,,,,,,,,,,,,,,,,,,
ISic000004,96.39,0.87,,,,,,,,,...,,,,,,,,,,
ISic000009grey,100.0,0.0,,,,,,,,,...,,,,,,,,,,
ISic000009pink,87.45,0.38,,,,,,,,,...,,,,,,8.24,0.33,,,Qcerussite; Qhydrotalcite
ISic000015,100.0,0.0,,,,,,,,,...,,,,,,,,,,
ISic000017,100.0,0.0,,,,,,,,,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
taoLastraR,99.6,0.11,0.0,0.0,,,0.225,0.074,,,...,,,,,,,,,,
taoPiedi,88.05,0.22,0.025,0.062,,,0.59,0.15,,,...,,,,,,,,,,
taoSarcofago,98.96,0.16,0.242,0.048,,,0.35,0.11,,,...,,,,,,,,,,
taomascherome,99.22,0.37,0.13,0.13,,,0.0,0.0,,,...,,,,,,,,,,
taoreclinato,99.591,0.084,0.07,0.021,,,0.0,0.0,,,...,,,,,,,,,,

In [7]:
xrd_converter.df_output

ESD (94.0) is larger than value (1.0) for ISic003373vg on qcalcite
ESD (1.3) is larger than value (0.0) for ISic003373vg on qquartz
ESD (96.0) is larger than value (0.0) for ISic003373vg on qchloritfxbg
ESD (0.0028) is larger than value (0.0016) for tao31 on qmusc2m1
ESD (0.00062) is larger than value (0.00025) for taoPiedi on qsio2p3121
ESD (0.76) is larger than value (0.54) for ISic001138pvg on qcalcite
ESD (0.024) is larger than value (0.017) for ISic001138pvg on qmusc2m1
ESD (0.91) is larger than value (0.36) for ISic001138pvg on qkaolinitedis
ESD (0.006) is larger than value (0.0042) for ISic001138pvg on qhematite
ESD (0.06) is larger than value (0.042) for ISic001138pvg on qchlorite2b
ESD (0.017) is larger than value (0.012) for ISic001138pvg on qquartz
ESD (0.024) is larger than value (0.017) for ISic001138pvg on qalbite
ESD (0.0048) is larger than value (0.0034) for ISic001138pvg on qenstatitemg06fe04ca
ESD (0.0089) is larger than value (0.0061) for ISic001138pvg on qenstatite
ESD (0.00047) is larger than value (0.00032) for ISic001138pvg on qsylvite
ESD (0.88) is larger than value (0.87) for ISic000068 on qcalcitmg
ESD (0.013) is larger than value (0.012) for ISic000068 on qdolomite
ESD (0.97) is larger than value (0.04) for ISic000068 on qiron
ESD (0.025) is larger than value (0.024) for ISic000068 on qgypsum
ESD (0.077) is larger than value (0.045) for ISic000163 on qcalcitmg
ESD (0.0021) is larger than value (0.0012) for ISic000163 on qdolomite
ESD (0.48) is larger than value (0.1) for ISic004363 on qcalcite
ESD (3.6) is larger than value (0.8) for ISic004363 on qcalcitmg
ESD (0.065) is larger than value (0.014) for ISic004363 on qdolomite
ESD (4.2) is larger than value (0.1) for ISic004363 on qiron

,XRD calcite content (%),XRD calcite content (%) ESD,XRD quartz content (%),XRD quartz content (%) ESD,XRD microcline content (%),XRD microcline content (%) ESD,XRD muscovite content (%),XRD muscovite content (%) ESD,XRD chlorite content (%),XRD chlorite content (%) ESD,...,XRD Na-sanidine content (%),XRD Na-sanidine content (%) ESD,XRD kaolinite content (%),XRD kaolinite content (%) ESD,XRD andesine content (%),XRD andesine content (%) ESD,XRD other minerals,XRD Clay Mineral,XRD K_Feldspar,XRD Plagioclase
Sample,,,,,,,,,,,,,,,,,,,,,
ISic000004,96.39,0.87,,,,,,,,,...,,,,,,,,0.000,0.0,0.00
ISic000009grey,100.0,0.0,,,,,,,,,...,,,,,,,,0.000,0.0,0.00
ISic000009pink,87.45,0.38,,,,,,,,,...,,,8.24,0.33,,,Qcerussite; Qhydrotalcite,8.240,0.0,0.00
ISic000015,100.0,0.0,,,,,,,,,...,,,,,,,,0.000,0.0,0.00
ISic000017,100.0,0.0,,,,,,,,,...,,,,,,,,0.000,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
taoLastraR,99.6,0.11,0.0,0.0,,,0.225,0.074,,,...,,,,,,,,0.225,0.0,0.00
taoPiedi,88.05,0.22,0.025,0.062,,,0.59,0.15,,,...,,,,,,,,0.590,0.0,0.00
taoSarcofago,98.96,0.16,0.242,0.048,,,0.35,0.11,,,...,,,,,,,,0.350,0.0,0.00
taomascherome,99.22,0.37,0.13,0.13,,,0.0,0.0,,,...,,,,,,,,0.000,0.0,0.46
taoreclinato,99.591,0.084,0.07,0.021,,,0.0,0.0,,,...,,,,,,,,0.000,0.0,0.00

In [12]:
xrd_converter.df_mineral_types

              subtype                      colname      category
0                   *           XRD other minerals
1             QALBINT       XRD albite content (%)   Plagioclase
2             Qalbint       XRD albite content (%)
3             QAlbite       XRD albite content (%)   Plagioclase
4           QAnalbite       XRD albite content (%)   Plagioclase
..                ...                          ...           ...
82          QSanina75  XRD Na-sanidine content (%)
83          QSANINA85  XRD Na-sanidine content (%)
84         QSiO2p3121       XRD quartz content (%)
85         QSiO2p3221       XRD quartz content (%)
86  Qsmectitedi2wfix1     XRD smectite content (%)  Clay Mineral

[87 rows x 3 columns]

In [ ]:
xrd_converter.df_output.loc['ISic000097']

ESD (94.0) is larger than value (1.0) for ISic003373vg on qcalcite
ESD (1.3) is larger than value (0.0) for ISic003373vg on qquartz
ESD (96.0) is larger than value (0.0) for ISic003373vg on qchloritfxbg
ESD (0.0028) is larger than value (0.0016) for tao31 on qmusc2m1
ESD (0.00062) is larger than value (0.00025) for taoPiedi on qsio2p3121
ESD (0.76) is larger than value (0.54) for ISic001138pvg on qcalcite
ESD (0.024) is larger than value (0.017) for ISic001138pvg on qmusc2m1
ESD (0.91) is larger than value (0.36) for ISic001138pvg on qkaolinitedis
ESD (0.006) is larger than value (0.0042) for ISic001138pvg on qhematite
ESD (0.06) is larger than value (0.042) for ISic001138pvg on qchlorite2b
ESD (0.017) is larger than value (0.012) for ISic001138pvg on qquartz
ESD (0.024) is larger than value (0.017) for ISic001138pvg on qalbite
ESD (0.0048) is larger than value (0.0034) for ISic001138pvg on qenstatitemg06fe04ca
ESD (0.0089) is larger than value (0.0061) for ISic001138pvg on qenstatite
ESD (0.00047) is larger than value (0.00032) for ISic001138pvg on qsylvite
ESD (0.88) is larger than value (0.87) for ISic000068 on qcalcitmg
ESD (0.013) is larger than value (0.012) for ISic000068 on qdolomite
ESD (0.97) is larger than value (0.04) for ISic000068 on qiron
ESD (0.025) is larger than value (0.024) for ISic000068 on qgypsum
ESD (0.077) is larger than value (0.045) for ISic000163 on qcalcitmg
ESD (0.0021) is larger than value (0.0012) for ISic000163 on qdolomite
ESD (0.48) is larger than value (0.1) for ISic004363 on qcalcite
ESD (3.6) is larger than value (0.8) for ISic004363 on qcalcitmg
ESD (0.065) is larger than value (0.014) for ISic004363 on qdolomite
ESD (4.2) is larger than value (0.1) for ISic004363 on qiron

KeyError: 'ISic000097'

In [ ]:
xrd_converter.run()

Postprocessing XRD data @ 2024-08-26 18:21:17,126
Saved: xrd_data_postprocessed.xlsx @ 2024-08-26 18:21:17,200